import { t, type Module } from "@/lib/types";

export const guardrails: Module = {
  id: "guardrails",
  n: 10,
  layer: 5,
  title: t("Guardrails and verification", "护栏与验证"),
  short: t(
    "Deterministic checks on tool calls and on answers, each one written from a real failure.",
    "对工具调用和回答做确定性检查，每一条都源自一次真实的失败。",
  ),
  what: t(
    "Guardrails are code that inspects what the agent is about to do or say. Hooks check tool calls before they run. An answer guard checks the draft against the evidence gathered in this request.",
    "护栏是检查智能体即将做什么、说什么的代码。钩子在工具调用执行前做检查。回答护栏把草稿与本次请求收集到的证据进行比对。",
  ),
  why: t(
    "Models produce fluent text whether or not it is supported. The reference agent once ran the right queries, got the right rows, and answered with an invented table. Only a check outside the model catches that.",
    "无论有没有依据，模型都能写出流畅的文字。参考智能体曾经执行了正确的查询、拿到了正确的数据，却给出了一张编造的表格。只有模型之外的检查才能发现这种情况。",
  ),
  how: [
    t("Extract the figures the draft states.", "提取草稿中陈述的数字。"),
    t("Collect evidence: numbers in tool results and in what the user said. The assistant's own earlier words are not evidence.", "收集证据：工具结果里的数字，以及用户说过的数字。助手自己之前说的话不算证据。"),
    t("A figure is grounded when it is in the evidence, or is the sum or difference of two evidence numbers.", "一个数字出现在证据中，或是两个证据数字的和或差，就算有依据。"),
    t("A failed draft gets one corrective message. The retry is judged by majority. If it still fails, a fixed fallback text is returned.", "草稿不通过时，给一次纠正提示。重试按多数规则判断。仍不通过就返回固定的兜底文本。"),
  ],
  prereqs: [
    {
      id: "harness",
      why: t("The guard is a stage in the loop, after the draft and before the response. Hooks wrap tool execution. Both need the loop's plug points.", "护栏是循环中的一个阶段，在草稿之后、响应之前。钩子包裹工具执行。两者都需要循环提供的接入点。"),
      stub: t("Run the guard offline over logged answers.", "离线对已记录的回答运行护栏。"),
    },
    {
      id: "tools-mcp",
      why: t("The guard compares the answer with tool results. Tools must return values it can parse.", "护栏把回答与工具结果比对。工具必须返回它能解析的值。"),
      stub: t("A fixed evidence string.", "一段固定的证据字符串。"),
    },
  ],
  inBuild: [
    { path: "apps/agent-server/answer_guard.py", role: t("Figure, count, and name checks. Corrective and fallback messages. Stream gate.", "数字、计数和名称检查。纠正提示和兜底文本。流式输出闸门。") },
    { path: "apps/agent-server/test_answer_guard.py", role: t("Regression tests, one per rule.", "回归测试，每条规则一个。") },
    { path: "apps/agent-server/hooks/write_path_guard.py", role: t("Blocks writes outside an allowed folder.", "阻止写入允许目录之外的位置。") },
  ],
  flow: {
    caption: t("What happens to a draft answer", "一份草稿回答会经历什么"),
    stages: [
      { label: t("Draft", "草稿"), detail: t("The model's answer, not yet shown to anyone.", "模型的回答，此时还没有展示给任何人。"), kind: "input" },
      { label: t("Should this turn be judged?", "这一轮需要判断吗？"), detail: t("Skip when the user asked for a made-up example, or when no tools ran on a non-data turn.", "用户明确要求举个虚构的例子时跳过；非数据轮次且没有运行工具时也跳过。"), kind: "check" },
      { label: t("Extract figures", "提取数字"), detail: t("Money amounts stated in the draft.", "草稿中陈述的金额。"), kind: "check" },
      { label: t("Compare with evidence", "与证据比对"), detail: t("Strict on the first draft: any unsupported figure fails.", "对第一稿从严：只要有一个数字没有依据就不通过。"), kind: "check" },
      { label: t("Corrective retry", "纠正重试"), detail: t("Name the unsupported figures and ask for a rewrite. Judge by majority.", "指出没有依据的数字，要求重写。按多数规则判断。"), kind: "model" },
      { label: t("Fallback", "兜底"), detail: t("If the retry fails, return a plain statement with no figures.", "如果重试仍不通过，返回一段不含数字的说明。"), kind: "output" },
    ],
  },
  steps: [
    {
      id: "collect",
      title: t("Start from logged failures", "从日志里的失败案例出发"),
      why: t("A guard written from imagination blocks the wrong things. Start with real answers that were wrong, so each rule has a case it must catch and you can find the cases it must allow.", "凭想象写的护栏会拦错东西。从真实的错误回答入手，这样每条规则都有它必须拦住的案例，你也能找到它必须放行的情况。"),
      do: [
        t("Read the request log. Collect answers that stated something the tools did not return.", "阅读请求日志。收集那些陈述了工具未返回内容的回答。"),
        t("For each, write what kind of thing was invented: an amount, a count, a name.", "对每一条，写下被编造的是哪类内容：金额、数量还是名称。"),
        t("Also collect answers that correctly state numbers from nowhere: a requested example, a well-known threshold.", "同时收集那些数字虽无来源却完全合理的回答：用户要求的示例、众所周知的阈值。"),
      ],
      verify: t("You have at least one must-catch case and one must-allow case.", "你至少有一个“必须拦住”的案例和一个“必须放行”的案例。"),
      needs: [{ step: "harness.run", what: t("the request log", "请求日志") }],
      produces: t("Two lists: must catch, must allow.", "两份清单：必须拦住的、必须放行的。"),
    },
    {
      id: "check",
      title: t("Write the grounding check", "编写依据检查"),
      why: t("The check is the core and has no dependencies, so it is written and tested alone before it touches the loop.", "这项检查是核心，而且没有任何依赖，所以先单独写好、测好，再接入循环。"),
      do: [
        t("`claims()` extracts money figures from the answer.", "`claims()` 从回答中提取金额。"),
        t("`evidence_numbers()` collects numbers from tool and user messages only.", "`evidence_numbers()` 只从工具消息和用户消息里收集数字。"),
        t("`grounded()` accepts a figure that is in the evidence or is a sum or difference of two evidence numbers.", "`grounded()` 接受出现在证据中的数字，或两个证据数字的和或差。"),
        t("`check()` is strict by default, and uses a majority rule when asked.", "`check()` 默认从严，按要求时使用多数规则。"),
      ],
      lab: { file: "labs/m10_guard/guard.py", region: "check" },
      run: "python3 -m labs.m10_guard.demo",
      output: "m10.demo",
      pick: ["1 "],
      verify: t("An exact figure passes, a derived total and difference pass, and an invented figure fails and is named.", "精确的数字通过；推算出的合计和差值通过；编造的数字不通过并被指出。"),
      needs: [{ step: "guardrails.collect", what: t("the kinds of figures to extract", "需要提取的数字类型") }],
      produces: t("`check()`: answer and messages to a verdict.", "`check()`：输入回答和消息，输出裁定。"),
    },
    {
      id: "review",
      title: t("Wrap the check in review(), with modes and exemptions", "用 review() 封装检查，加入模式和豁免"),
      why: t("The loop needs one function that also knows when not to judge. The exemptions come from your must-allow list.", "循环需要的是一个函数，它还得知道什么时候不该判断。豁免规则来自你的“必须放行”清单。"),
      do: [
        t("Skip when the user asked for a made-up example.", "用户要求举虚构的例子时跳过。"),
        t("Skip when no tool ran and the turn is not a data turn. General talk may quote a threshold.", "没有运行工具且不是数据轮次时跳过。一般性的交谈可以引用某个阈值。"),
        t("Read a mode from the environment: enforce, observe, or off.", "从环境变量读取模式：enforce、observe 或 off。"),
        t("Return the verdict with a corrective message that names the figures, and a fallback text.", "返回裁定，并附上指出具体数字的纠正提示和兜底文本。"),
      ],
      lab: { file: "labs/m10_guard/guard.py", region: "review" },
      output: "m10.demo",
      pick: ["4 ", "5 "],
      verify: t("A requested example passes, and a turn with no tools is marked as not a data turn.", "用户要求的示例通过；没有工具的轮次被标记为非数据轮次。"),
      needs: [
        { step: "guardrails.check", what: t("check()", "check()") },
        { step: "skills.inject", what: t("the skill name, which marks a data turn", "技能名，用来标识数据轮次") },
      ],
      produces: t("`review()`: the function the harness calls.", "`review()`：Harness 调用的函数。"),
    },
    {
      id: "observe",
      title: t("Run in observe mode first", "先以观察模式运行"),
      why: t("Before the guard changes any answer, measure how often it would fire on real traffic and what it would wrongly block.", "在护栏改变任何回答之前，先测量它在真实流量上会触发多少次、会误拦什么。"),
      do: [
        t("Set the mode to observe and attach the guard to the agent.", "把模式设为 observe，并把护栏接到智能体上。"),
        t("Let it log would-block decisions for a period.", "让它在一段时间内记录“本应拦截”的决定。"),
        t("Read each one. Add an exemption for every legitimate case.", "逐条查看。为每个合理的情况添加豁免。"),
      ],
      output: "m10.demo",
      pick: ["3 "],
      verify: t("In observe mode the fabricated answer is left alone and `would_block` is True.", "观察模式下，编造的回答原样保留，`would_block` 为 True。"),
      needs: [{ step: "guardrails.review", what: t("the mode switch", "模式开关") }],
      produces: t("A list of would-block cases reviewed by a person.", "一份经人工审阅的“本应拦截”案例清单。"),
    },
    {
      id: "retry",
      title: t("Enforce: corrective retry, then fallback", "强制执行：先纠正重试，再兜底"),
      why: t("This joins the guard to the loop. It follows observation because now you know the guard's false positives.", "这一步把护栏接到循环上。它排在观察之后，因为此时你已经了解了护栏的误报情况。"),
      do: [
        t("Pass `review` as the `guard` argument of the agent.", "把 `review` 作为智能体的 `guard` 参数传入。"),
        t("Run three models: honest, one that invents a figure once, one that keeps inventing.", "运行三种模型：诚实的、编造一次数字的、持续编造的。"),
        t("Read the three outcomes: pass, corrected on retry, fallback.", "看三种结果：通过、重试后被纠正、兜底。"),
      ],
      code: { lang: "python", text: `from labs.m10_guard.guard import review

agent = Agent(registry, skills=router.match, guard=review)` },
      output: "m10.demo",
      pick: ["2 "],
      verify: t("The second line shows retried=True with a grounded answer. The third shows the fallback text.", "第二行显示 retried=True 且回答有依据。第三行显示兜底文本。"),
      needs: [
        { step: "guardrails.observe", what: t("confidence in the exemptions", "对豁免规则的信心") },
        { step: "harness.run", what: t("the guard plug point and retry path", "护栏接入点和重试路径") },
      ],
      produces: t("An agent that cannot return an unsupported figure on a data turn.", "一个在数据轮次上无法返回无依据数字的智能体。"),
    },
    {
      id: "hooks",
      title: t("Add a pre-tool hook for writes", "为写操作加一个工具前置钩子"),
      why: t("Hooks are the other half: they act before a tool runs. This one is independent of the answer guard and can be built at any point after the harness has its hook list.", "钩子是另一半：它们在工具运行之前起作用。这一个与回答护栏无关，只要 Harness 有了钩子列表，随时可以搭建。"),
      do: [
        t("Resolve the target path, so `..` and symlinks are followed before the test.", "先解析目标路径，让 `..` 和符号链接在判断之前就被展开。"),
        t("Block when the resolved path is outside the allowed folder.", "解析后的路径在允许目录之外时，阻止操作。"),
        t("Return nothing for tools that do not write.", "对不执行写操作的工具，什么都不返回。"),
      ],
      lab: { file: "labs/m10_guard/hooks.py", region: "hook" },
      output: "m10.demo",
      pick: ["6 ", "7 "],
      verify: t("A relative path inside the folder is allowed. A path that climbs out and an absolute path elsewhere are blocked.", "目录内的相对路径被允许。向上跳出目录的路径和指向别处的绝对路径被阻止。"),
      needs: [{ step: "harness.hooks", what: t("the hook list", "钩子列表") }],
      produces: t("`write_path_guard()`: a hook factory.", "`write_path_guard()`：钩子工厂函数。"),
    },
    {
      id: "regress",
      title: t("Keep one regression test per rule", "每条规则保留一个回归测试"),
      why: t("Last, because every rule now exists. A guard grows one rule at a time, and without tests a new rule breaks an old exemption.", "放在最后，因为此时所有规则都已存在。护栏是一条一条规则加出来的，没有测试的话，新规则会破坏旧的豁免。"),
      do: [
        t("For each must-catch case, write a test that fails the guard.", "为每个“必须拦住”的案例写一个让护栏不通过的测试。"),
        t("For each must-allow case, write a test that passes it.", "为每个“必须放行”的案例写一个让护栏通过的测试。"),
        t("Run them before every change to the guard, and keep test traffic out of the production guard log. The lab guard writes no log, so the lab tests only the first part.", "每次修改护栏前都运行它们，并且不要让测试流量进入生产环境的护栏日志。lab 里的护栏不写日志，所以 lab 只测试前一部分。"),
      ],
      lab: { file: "labs/m10_guard/test_guard.py" },
      run: "python3 -m labs.m10_guard.run_tests",
      output: "m10.tests",
      verify: t("11 tests pass: each rule has a case it must catch and a case it must allow.", "11 个测试全部通过：每条规则都有一个必须拦住的案例和一个必须放行的案例。"),
      needs: [
        { step: "guardrails.collect", what: t("the two case lists", "两份案例清单") },
        { step: "guardrails.review", what: t("the functions under test", "被测试的函数") },
      ],
      produces: t("A test file that grows with the guard.", "一个随护栏一起增长的测试文件。"),
    },
  ],
  together: [
    { with: "harness", how: t("The loop calls review() on the draft and each hook before each tool call.", "循环对草稿调用 review()，并在每次工具调用前调用各个钩子。") },
    { with: "tools-mcp", how: t("Tool messages are the evidence. Structured results make figures easy to find.", "工具消息就是证据。结构化的结果让数字容易被找到。") },
    { with: "evaluation", how: t("The agent eval reuses check() to grade whether figures are grounded.", "智能体评估复用 check() 来判断数字是否有依据。") },
    { with: "self-evolving", how: t("The promotion gate is a guard on stored knowledge: support must be independent.", "晋升关卡是针对已存储知识的护栏：支持证据必须相互独立。") },
  ],
  failures: [
    {
      when: "2026-10",
      title: t("An answer with no tool call passed unchecked", "没有工具调用的回答未经检查就通过了"),
      what: t("A follow-up question was answered with three invented totals and no query. The guard ran only when tools had been called.", "一个追问被直接回答了三个编造的合计数，没有执行任何查询。当时护栏只在调用过工具时才运行。"),
      fix: t("On data turns, check tool-free answers against the conversation so far.", "在数据轮次上，对没有调用工具的回答也要对照已有对话进行检查。"),
      lesson: t("Decide what the default is when a check has nothing to compare against.", "当检查没有可比对的对象时，默认行为是什么，要事先决定。"),
    },
    {
      when: "2026-10",
      title: t("The guard blocked a requested example", "护栏拦住了用户要求的示例"),
      what: t("A user asked for a made-up numeric example. The guard rejected the invented amounts and the user got an apology.", "用户要求举一个虚构的数字示例。护栏拒绝了这些虚构的金额，用户只得到一句道歉。"),
      fix: t("Detect explicit requests for examples and skip the figure check on that turn.", "识别明确要求举例的请求，在该轮跳过数字检查。"),
      lesson: t("Every guard needs a list of legitimate cases it must let through, with tests.", "每个护栏都需要一份必须放行的合理情况清单，并配上测试。"),
    },
    {
      when: "2026-10",
      title: t("Four right totals and one wrong one passed", "四个对的合计加一个错的，通过了"),
      what: t("A majority rule let through an answer with one wrong figure among four right ones.", "多数规则放过了一个四对一错的回答。"),
      fix: t("Judge the first draft strictly. Use the majority rule only on the retry.", "对第一稿从严判断。多数规则只用于重试。"),
      lesson: t("Strict first, lenient second: catch the single error, and do not turn one stubborn figure into a refusal.", "先严后宽：既要抓住单个错误，也不要因为一个纠正不过来的数字就把整个回答变成拒绝。"),
    },
    {
      when: "2026-10",
      title: t("Right figures from the wrong source", "数字是对的，来源是错的"),
      what: t("Once in six runs a spending question was answered from a web search while the data tools were never called. Every figure matched the web result, so the check passed.", "六次运行中有一次，一个支出问题是根据网页搜索回答的，数据工具根本没被调用。每个数字都与网页结果一致，所以检查通过了。"),
      fix: t("On a data turn, reject a first draft that cites figures after a web search and no data tool.", "在数据轮次上，如果第一稿只做了网页搜索、没有调用数据工具就引用数字，则拒绝。"),
      lesson: t("Grounded is not the same as grounded in the right source.", "“有依据”不等于“依据来自正确的来源”。"),
    },
  ],
  portability: {
    databricks: t(
      "Unity Gateway applies guardrails at the endpoint. Groundedness checks like this one are custom code in your agent, or scorers such as RetrievalGroundedness run on traces.",
      "Unity Gateway 在端点层面应用护栏。像这样的依据检查需要你在智能体里自己写，或用 RetrievalGroundedness 这类 scorer 在 trace 上运行。",
    ),
    watsonx: t("watsonx.governance provides guardrails and monitors. Domain checks go in a tool or a post-processing step you write.", "watsonx.governance 提供护栏和监控。业务领域的检查要放在工具里，或你自己写的后处理步骤里。"),
    codex: t("Sandbox and approval modes limit actions. Hooks and your own test commands act as checks on changes.", "沙箱和审批模式限制操作。钩子和你自己的测试命令充当对改动的检查。"),
    cursor: t("Hooks can block or modify agent actions. Rules can require checks before completion.", "钩子可以阻止或修改智能体的操作。规则可以要求在完成前执行检查。"),
    claude: t("Hooks run before and after tool use and can block. Permission modes limit actions. Output checks are code you add in hooks or in the SDK loop.", "钩子在工具使用前后运行，可以阻止操作。权限模式限制操作范围。输出检查是你在钩子或 SDK 循环里添加的代码。"),
    other: t("The guard is a pure Python module that takes an answer and messages. Portable as is.", "护栏是一个纯 Python 模块，输入回答和消息即可。可以原样移植。"),
  },
  checks: [
    {
      q: t("Why judge the first draft strictly and the retry by majority?", "为什么第一稿从严、重试按多数规则？"),
      a: t("A strict first pass catches a single wrong figure among right ones. A lenient retry keeps one stubborn figure from turning a usable answer into a refusal.", "第一遍从严，能抓住混在正确数字里的单个错误。重试从宽，避免一个纠正不过来的数字把可用的回答变成拒绝。"),
    },
    {
      q: t("Why does every rule need an observe mode?", "为什么每条规则都需要观察模式？"),
      a: t("So you can measure how often it would fire on real traffic, and what it would wrongly block, before it changes any answer.", "这样可以在它改变任何回答之前，先测出它在真实流量上的触发频率，以及会误拦什么。"),
    },
    {
      q: t("Why is the assistant's earlier text excluded from evidence?", "为什么助手之前说的话不算证据？"),
      a: t("If it counted, a figure invented in one turn would ground itself in the next. Evidence is what tools returned and what the user supplied.", "如果算证据，上一轮编造的数字到下一轮就成了自己的依据。证据只包括工具返回的内容和用户提供的内容。"),
    },
    {
      q: t("What is the difference between a hook and the answer guard?", "钩子和回答护栏有什么区别？"),
      a: t("A hook runs before a tool call and can stop an action. The guard runs after the draft and can stop a statement. One protects the world from the agent, the other protects the reader.", "钩子在工具调用之前运行，可以阻止一个动作。护栏在草稿之后运行，可以阻止一句陈述。前者保护外部环境不受智能体影响，后者保护读者。"),
    },
  ],
  terms: [
    { term: t("Grounded", "有依据"), def: t("Present in the evidence of this request, or derived from it by a simple rule.", "出现在本次请求的证据中，或可由简单规则从证据推出。") },
    { term: t("Data turn", "数据轮次"), def: t("A turn where a data skill was loaded, so figures are expected to come from tools.", "加载了数据类技能的轮次，其中的数字应当来自工具。") },
    { term: t("Observe mode", "观察模式"), def: t("The guard records what it would block and changes nothing.", "护栏只记录它本来会拦截什么，不改变任何结果。") },
    { term: t("Fallback", "兜底文本"), def: t("A fixed, figure-free reply used when a retry also fails.", "重试仍不通过时使用的、不含数字的固定回复。") },
  ],
};
