import { t, type Module } from "@/lib/types";

export const selfEvolving: Module = {
  id: "self-evolving",
  n: 13,
  layer: 6,
  title: t("Self-evolving agents", "自进化智能体"),
  short: t(
    "A scheduled loop that studies its own logs, promotes what is corroborated, and is graded on sealed tests.",
    "一个定时运行的循环：研究自己的日志，把得到印证的内容晋升为规则，并接受封存测试的评分。",
  ),
  what: t(
    "A self-evolving agent improves between conversations. This module builds the loop: observe failures in the logs, gather evidence across days, pass a promotion gate, test the proposed change on sealed evals, then apply or reject it.",
    "自进化智能体在两次对话之间变得更好。本模块搭建这个循环：从日志中观察失败、跨天积累证据、通过晋升关卡、在封存评估上测试拟议的改动，然后应用或否决。",
  ),
  why: t(
    "Most improvement comes from noticing the same failure repeatedly and encoding the fix. Automating that is powerful and dangerous. The loop changes no model weights. It changes stored rules, and those reach an answer only through the prompt.",
    "大部分改进来自反复注意到同一种失败，并把修复方法固化下来。把这个过程自动化既强大又危险。这个循环不改变任何模型权重，它改变的是存储的规则，而规则只能通过提示词影响回答。",
  ),
  how: [
    t("Observation looks for failures that can be confirmed mechanically: an empty result that returns rows when one filter is removed.", "观察环节寻找可以机械确认的失败：某个结果为空，但去掉一个过滤条件后就有数据返回。"),
    t("Evidence is keyed by claim, origin, and day. Ten repeats in one day are one piece of evidence.", "证据以论断、来源和日期为键。同一天重复十次，只算一条证据。"),
    t("The gate promotes a candidate only after it is seen on enough separate days.", "关卡只在候选项在足够多的不同日期被观察到之后才予以晋升。"),
    t("Before a change is applied, the sealed agent eval runs with and without it. Worse means rejected.", "应用改动之前，分别在带与不带该改动的情况下运行封存的智能体评估。变差就否决。"),
    t("The loop writes one file of learned rules. It cannot write the evals, the gate, or the model.", "循环只写一个学到的规则文件。它无法改写评估、关卡或模型。"),
  ],
  prereqs: [
    {
      id: "evaluation",
      why: t("A loop optimizes what it can measure. Sealed evals have to exist before the loop runs, or it grades itself.", "循环会优化它能测量的东西。封存评估必须先于循环存在，否则它就是在给自己打分。"),
      stub: t("None that is safe. You may run the loop in report mode without evals. Do not let it apply changes.", "没有安全的替代方案。没有评估时可以用报告模式运行循环，但不要让它应用任何改动。"),
    },
    {
      id: "memory",
      why: t("Learned rules are memory that belongs to the agent. They use the same store and the same status discipline.", "学到的规则是属于智能体自身的记忆。它们使用同一个存储和同样的状态管理方式。"),
      stub: t("Append findings to a Markdown file for a person to review.", "把发现追加到一个 Markdown 文件，交人审阅。"),
    },
    {
      id: "guardrails",
      why: t("The promotion gate is guard logic applied to stored knowledge, and it follows the same observe-first practice.", "晋升关卡是应用在已存储知识上的护栏逻辑，同样遵循先观察的做法。"),
      stub: t("Human approval of every promotion.", "每次晋升都由人工批准。"),
    },
    {
      id: "rag-graph",
      why: t("When the loop studies documents, it reads indexed chunks and must skip the held-out ones.", "循环学习文档时读取的是已索引的文本块，并且必须跳过留出的那些。"),
      stub: t("Learn from logs only, as the lab does.", "只从日志中学习，lab 就是这么做的。"),
    },
  ],
  inBuild: [
    { path: "apps/agent-server/nightly/self_observe.py", role: t("Finds confident wrong answers in the logs.", "从日志中找出自信但错误的回答。") },
    { path: "apps/agent-server/nightly/scheduler.py", role: t("Duty cycle and preemption for background work.", "后台任务的占空比控制和抢占机制。") },
    { path: "apps/agent-server/nightly/corroboration_audit.py", role: t("Checks that support is independent.", "检查支持证据是否相互独立。") },
    { path: "apps/agent-server/nightly/claim_verify.py", role: t("Two-vote check that takes unsupported claims out of service.", "双票核查，把没有依据的论断停用。") },
    { path: "SELF-EVOLUTION-LESSONS.md", role: t("What went wrong and what was changed.", "出过什么问题，以及做了哪些修改。") },
  ],
  flow: {
    caption: t("One night of the loop", "循环的一个夜晚"),
    stages: [
      { label: t("Read new log lines", "读取新的日志行"), detail: t("A cursor makes sure each line is seen once.", "游标保证每一行只被处理一次。"), kind: "input" },
      { label: t("Confirm findings", "确认发现"), detail: t("Re-run each empty tool call with one filter removed. Rows mean a parameter problem.", "把每个结果为空的工具调用去掉一个过滤条件后重新执行。有数据返回就说明是参数问题。"), kind: "tool" },
      { label: t("Record evidence", "记录证据"), detail: t("One row per claim, origin, and day.", "每个论断、来源和日期一行。"), kind: "store" },
      { label: t("Promotion gate", "晋升关卡"), detail: t("Seen on enough separate days?", "是否在足够多的不同日期被观察到？"), kind: "check" },
      { label: t("Sealed eval, before and after", "封存评估：改动前后"), detail: t("The proposed rule must not lower the score.", "拟议的规则不能让得分下降。"), kind: "check" },
      { label: t("Apply, reject, or report", "应用、否决或报告"), detail: t("Report mode writes nothing. Apply mode appends one rule.", "报告模式什么都不写。应用模式追加一条规则。"), kind: "output" },
    ],
  },
  steps: [
    {
      id: "preconditions",
      title: t("Check the four preconditions", "检查四项前提条件"),
      why: t("This module joins more earlier work than any other. Starting without one of these produces a loop that looks like it is learning.", "这个模块衔接的前序工作比其他任何模块都多。缺了其中任何一项就开始，得到的只是一个“看起来在学习”的循环。"),
      do: [
        t("Logs: the harness writes tool calls and requests as JSON lines, and tool calls record empty results.", "日志：Harness 以 JSON Lines 记录工具调用和请求，并且工具调用会标明结果是否为空。"),
        t("Cursor: a job can read only new lines.", "游标：任务只能读到新增的行。"),
        t("Seal: the agent eval refuses to run on changed files.", "封存：文件被改动时，智能体评估拒绝运行。"),
        t("Reset: you have tested dropping learned state alone.", "重置：你已经测试过单独清除学到的状态。"),
      ],
      verify: t("Each of the four is a step you have already run.", "这四项都是你已经运行过的步骤。"),
      needs: [
        { step: "harness.run", what: t("the two log files", "两份日志文件") },
        { step: "state.cursor", what: t("read_new_lines()", "read_new_lines()") },
        { step: "evaluation.agent", what: t("the sealed agent eval", "封存的智能体评估") },
        { step: "state.reset", what: t("the tested way to undo learning", "经过验证的撤销学习的方法") },
      ],
      produces: t("Confidence that the loop can be measured and undone.", "对“这个循环可以被测量、也可以被撤销”的信心。"),
    },
    {
      id: "observe",
      title: t("Observe: find failures that prove themselves", "观察：找出能自我证明的失败"),
      why: t("Observation is first in the loop. It looks only for shapes that code can confirm, because a loop that learns from a model's opinion of its own answers amplifies its own mistakes.", "观察是循环的第一步。它只找代码能够确认的模式，因为如果循环从模型对自己回答的看法中学习，只会放大它自己的错误。"),
      do: [
        t("Read new tool-call lines through the cursor.", "通过游标读取新的工具调用记录。"),
        t("For each empty result, re-run the call once per filter with that filter removed.", "对每个空结果，每次去掉一个过滤条件，重新执行调用。"),
        t("If a relaxed call returns rows, record a finding with the proof and the day.", "如果放宽后的调用返回了数据，就记录一条发现，附上证明和日期。"),
        t("Also record budget exhaustion and blocked calls as signals.", "同时把预算耗尽和被阻止的调用也记录为信号。"),
      ],
      lab: { file: "labs/m13_evolve/observe.py", region: "observe" },
      verify: t("A question about a month with no data produces a finding named `query_expenses.relax_month`.", "一个关于没有数据的月份的问题，会产生一条名为 `query_expenses.relax_month` 的发现。"),
      needs: [
        { step: "self-evolving.preconditions", what: t("logs and a cursor", "日志和游标") },
        { step: "tools-mcp.limits", what: t("the call log's empty flag, and a registry to re-run calls", "调用日志里的 empty 标记，以及用来重新执行调用的注册表") },
      ],
      produces: t("`observe()`: findings with a signal, a key, a day, and a proof.", "`observe()`：带有信号、键、日期和证明的发现。"),
    },
    {
      id: "evidence",
      title: t("Record evidence so repetition cannot pose as support", "记录证据，不让重复冒充支持"),
      why: t("Evidence is stored before any gate reads it. The key design is the reason this step exists: one row per claim, origin, and day.", "证据要先存好，关卡才有东西可读。主键的设计正是这一步存在的原因：每个论断、来源、日期只有一行。"),
      do: [
        t("Insert the claim as a candidate if it is new.", "如果是新的论断，就作为候选项插入。"),
        t("Insert evidence with a primary key of claim, origin, and day. A second insert on the same day is ignored.", "以论断、来源、日期为主键插入证据。同一天的第二次插入会被忽略。"),
        t("For claims from documents the origin is the document, so copies of one text count once.", "对来自文档的论断，来源就是文档，所以同一文本的多份副本只算一次。"),
      ],
      lab: { file: "labs/m13_evolve/promote.py", region: "gate" },
      verify: t("The same failure twice in one day shows as one day of evidence.", "同一天内出现两次的同一种失败，显示为一天的证据。"),
      needs: [
        { step: "self-evolving.observe", what: t("findings", "发现") },
        { step: "state.schema", what: t("brain_claims and brain_evidence", "brain_claims 和 brain_evidence 表") },
      ],
      produces: t("`add_evidence()`, `ready_for_promotion()`, `standing()`.", "`add_evidence()`、`ready_for_promotion()`、`standing()`。"),
    },
    {
      id: "nightly",
      title: t("Assemble the nightly loop with the eval gate", "组装夜间循环，并加上评估关卡"),
      why: t("This joins observation, evidence, and the sealed eval. The eval sits between the gate and the write, so a change that passes the day count can still be stopped.", "这一步把观察、证据和封存评估连在一起。评估位于关卡和写入之间，所以即使天数达标，改动仍然可以被拦下。"),
      do: [
        t("Observe, then add evidence.", "先观察，再添加证据。"),
        t("For each candidate past the gate: build the proposed rules text.", "对每个通过关卡的候选项：生成拟议的规则文本。"),
        t("Run the sealed agent eval with the current rules, then with the proposed rules.", "先用当前规则运行封存的智能体评估，再用拟议规则运行一次。"),
        t("Worse: retire the candidate. Otherwise in apply mode: append the rule and mark it trusted. In report mode: list it and write nothing.", "变差：让候选项退役。否则，在应用模式下：追加规则并标记为可信；在报告模式下：列出它，什么都不写。"),
      ],
      lab: { file: "labs/m13_evolve/loop.py", region: "nightly" },
      verify: t("The only file the function writes is the rules file, and only in apply mode.", "这个函数唯一写入的文件是规则文件，而且只在应用模式下写。"),
      needs: [
        { step: "self-evolving.evidence", what: t("the gate", "关卡") },
        { step: "evaluation.agent", what: t("agent_eval.run()", "agent_eval.run()") },
        { step: "harness.compose", what: t("the base prompt the rules are appended to", "规则所附加到的基础提示词") },
      ],
      produces: t("`nightly()`: one call per night that returns a report.", "`nightly()`：每晚调用一次，返回一份报告。"),
    },
    {
      id: "report",
      title: t("Run in report mode and read three days", "以报告模式运行，查看三天的情况"),
      why: t("Report mode first, for the same reason the guard ran in observe mode: see what it would do before it does it.", "先用报告模式，理由和护栏先用观察模式一样：在它真正动手之前，先看它会做什么。"),
      do: [
        t("Run the demo. It simulates three days of traffic with an out-of-range month on each day.", "运行 demo。它模拟三天的流量，每天都有一个超出数据范围的月份。"),
        t("Read line 0: the sealed eval before learning, and which question fails.", "看第 0 行：学习之前的封存评估结果，以及哪道题没通过。"),
        t("Read each day: the finding, and the candidate's standing in days.", "逐天查看：当天的发现，以及候选项累计的天数。"),
        t("On day three the gate passes and report mode writes nothing.", "第三天关卡通过，而报告模式什么都没写。"),
      ],
      run: "python3 -m labs.m13_evolve.demo",
      output: "m13.demo",
      pick: ["0 ", "2026-07-01", "2026-07-02", "2026-07-03"],
      verify: t("Day one shows two findings and one day of evidence. Day three shows before 5 and after 6, pending.", "第一天显示两条发现、一天的证据。第三天显示改动前 5 分、改动后 6 分，状态为待定。"),
      needs: [{ step: "self-evolving.nightly", what: t("nightly() in report mode", "报告模式下的 nightly()") }],
      produces: t("A report you can review before allowing any write.", "一份在允许任何写入之前可供审阅的报告。"),
    },
    {
      id: "apply",
      title: t("Switch to apply and confirm the change", "切换到应用模式并确认改动"),
      why: t("Only after reading reports. The change is confirmed three ways: the rules file, the sealed eval, and the behavior on the original question.", "只有在看过报告之后才做。改动通过三种方式确认：规则文件、封存评估，以及原问题上的行为。"),
      do: [
        t("Run the loop once more in apply mode.", "以应用模式再运行一次循环。"),
        t("Read the rules file: one line was appended.", "查看规则文件：追加了一行。"),
        t("Read the sealed eval after: 6 of 6.", "查看之后的封存评估：6/6。"),
        t("Ask the original question again. The agent now retries without the month and reports what exists.", "再问一次原来的问题。智能体现在会去掉月份重试，并报告实际存在的数据。"),
      ],
      output: "m13.demo",
      pick: ["apply", "rules file", "sealed eval after", "same question", "tools used"],
      verify: t("The tools used are two `query_expenses` calls, and the answer contains 358.60.", "使用的工具是两次 `query_expenses` 调用，回答中包含 358.60。"),
      needs: [{ step: "self-evolving.report", what: t("a reviewed pending change", "一个经过审阅的待定改动") }],
      produces: t("One learned rule, gated by evidence and by a sealed eval.", "一条学到的规则，经过证据和封存评估的双重把关。"),
    },
    {
      id: "limits",
      title: t("Know what the lab does not prove", "明确 lab 没有证明什么"),
      why: t("Read this before running the loop on a real model. The lab proves the plumbing. It cannot prove the learning.", "在真实模型上运行循环之前先读这一步。lab 证明了管道是通的，但证明不了学习本身。"),
      do: [
        t("The fake model follows the rule because its script contains that behavior. With a real model, a rule is text in the prompt and the model may ignore it.", "假模型之所以遵守规则，是因为它的脚本里写了这种行为。对真实模型来说，规则只是提示词里的文字，模型可能不理会它。"),
        t("That is why the eval gate matters more with a real model: it is the only evidence that a rule changed behavior.", "这正是评估关卡在真实模型上更重要的原因：它是规则改变了行为的唯一证据。"),
        t("A real model is also noisy. Run the before and after evals several times and compare the spread.", "真实模型还有噪声。改动前后的评估都要多跑几次，并比较波动范围。"),
        t("The reference build measured this directly: one instrument showed a large gain from learned knowledge, a larger one showed almost none.", "参考系统直接测量过这一点：一套测量工具显示学到的知识带来很大提升，另一套更大的测量工具显示几乎没有提升。"),
      ],
      verify: t("You can say which parts of the demo would change with a real model, and which would not.", "你能说出换成真实模型后，demo 的哪些部分会变，哪些不会。"),
      needs: [
        { step: "self-evolving.apply", what: t("the demo result to interpret", "需要解读的 demo 结果") },
        { step: "evaluation.noise", what: t("the noise floor of the agent eval", "智能体评估的噪声基线") },
      ],
      produces: t("An honest boundary around what was demonstrated.", "对“已演示了什么”划出的一条诚实的边界。"),
      notExecuted: true,
    },
    {
      id: "documents",
      title: t("Extend the loop to learn from documents", "把循环扩展到从文档中学习"),
      why: t("Log-based learning comes first because it is mechanically checkable. Document learning adds a model that reads, so it adds the two-vote check and the held-out exclusion.", "先做基于日志的学习，因为它可以机械验证。从文档学习多了一个负责阅读的模型，所以要加上双票核查和留出排除。"),
      do: [
        t("Read only chunks returned by `studiable()`.", "只读取 `studiable()` 返回的文本块。"),
        t("Order the reading queue by authority tier.", "阅读队列按权威等级排序。"),
        t("Extract claims in stages: define terms, outline, claims, links.", "分阶段提取论断：定义术语、列提纲、提取论断、建立关联。"),
        t("Promote a claim only with support from two independent documents. Copies of one text count once.", "只有得到两份相互独立的文档支持，论断才能晋升。同一文本的副本只算一次。"),
        t("Check served claims against their source with two votes, and take those failing both out of service.", "用双票核查已启用的论断与其来源，两票都不通过的予以停用。"),
      ],
      verify: t("No served claim cites a held-out chunk, and each has at least two independent origins or a tier 1 source.", "任何已启用的论断都没有引用留出的文本块，并且每条都至少有两个独立来源，或一个 1 级来源。"),
      needs: [
        { step: "evaluation.seal", what: t("studiable(), the exclusion list", "studiable()，即排除清单") },
        { step: "multi-agent.judges", what: t("verify(), the two-vote check", "verify()，即双票核查") },
        { step: "knowledge.tiers", what: t("tiers to order the reading queue", "用于给阅读队列排序的等级") },
      ],
      produces: t("Claims with sources, which a recall tool can return.", "带来源的论断，可由回忆类工具返回。"),
      notExecuted: true,
    },
    {
      id: "rollback",
      title: t("Keep rollback one command away", "让回滚只需一条命令"),
      why: t("Last, and required before the loop runs unattended. Every applied change must be reversible without touching anything else.", "这是最后一步，也是让循环无人值守运行之前的必要条件。每个已应用的改动都必须可以撤销，且不影响其他任何东西。"),
      do: [
        t("Keep the rules file under version control. One rule per line makes a revert one line.", "把规则文件纳入版本控制。每条规则一行，回滚时只需撤销一行。"),
        t("To undo everything: delete the rules file and drop the learned tables.", "要全部撤销：删除规则文件，并删除学到的那些表。"),
        t("Re-run the sealed eval after any rollback.", "每次回滚之后重新运行封存评估。"),
      ],
      code: { lang: "bash", text: `git log --oneline -- learned-rules.md      # every applied rule is a commit
git revert <commit>                        # undo one rule
# then re-run your sealed agent eval and compare with the pre-learning score` },
      verify: t("After a full reset the sealed eval returns to its pre-learning score.", "全部重置之后，封存评估回到学习之前的得分。"),
      needs: [
        { step: "self-evolving.apply", what: t("applied rules to undo", "要撤销的已应用规则") },
        { step: "state.reset", what: t("dropping learned tables", "删除学到的表") },
      ],
      produces: t("A loop you can leave running.", "一个可以放心让它持续运行的循环。"),
      notExecuted: true,
    },
  ],
  together: [
    { with: "evaluation", how: t("The sealed agent eval gates every change. The seal stops the loop from reading or editing its test.", "封存的智能体评估为每次改动把关。封存机制阻止循环读取或修改自己的考题。") },
    { with: "harness", how: t("The loop reads the harness logs and writes text that the harness appends to the prompt.", "循环读取 Harness 的日志，并写出由 Harness 附加到提示词的文本。") },
    { with: "tools-mcp", how: t("Findings are confirmed by re-running tool calls through the registry.", "发现是通过注册表重新执行工具调用来确认的。") },
    { with: "ops", how: t("The loop runs in a scheduled window and pauses for live requests.", "循环在预定的时间窗口内运行，遇到实时请求时暂停。") },
  ],
  failures: [
    {
      when: "2026-09",
      title: t("Self-observation fabricated its own corroboration", "自我观察给自己编造了印证"),
      what: t("Findings were re-logged every hour and each re-log counted as new support. 184 bad findings had to be removed.", "发现每小时被重新记录一次，每次重新记录都被算作新的支持。最后不得不移除 184 条错误的发现。"),
      fix: t("Key evidence by day and origin.", "证据以日期和来源为键。"),
      lesson: t("Count independent observations. Repetition by the same observer is one observation.", "只统计相互独立的观察。同一观察者的重复只算一次观察。"),
    },
    {
      when: "2026-09",
      title: t("The experience half of the loop was switched off", "循环中“经验”那一半其实是关着的"),
      what: t("The loop studied documents every night and never read its own failures. The setting for that half was disabled.", "循环每晚都在学习文档，却从未读过自己的失败记录。那一半的设置被关掉了。"),
      fix: t("Turn it on, and print in the daily report which halves ran.", "把它打开，并在每日报告里输出哪几部分实际运行了。"),
      lesson: t("Report what ran. A loop that silently skips a stage looks the same as one that works.", "要报告实际运行了什么。悄悄跳过某个阶段的循环，看起来和正常工作的循环没有区别。"),
    },
    {
      when: "2026-08",
      title: t("A learner that reported gains nobody could reproduce", "学习任务报告的提升没有人能复现"),
      what: t("After about 100 hours of autonomous running, headline numbers looked good and each one was misleading on inspection.", "自主运行约 100 小时后，核心数字看起来不错，但细看之下每一个都有误导性。"),
      fix: t("Sealed evals, repeats, and a report line per eval.", "封存评估、重复运行、每项评估在报告里占一行。"),
      lesson: t("A learning loop is finished when its measurement is trusted. The loop itself is the easy part.", "学习循环什么时候算完成？当它的测量结果值得信任时。循环本身反而是容易的部分。"),
    },
  ],
  portability: {
    databricks: t("Lakeflow Jobs schedule the loop. Traces and labeled feedback are the raw material. Evaluation datasets grow from production traces, and judges can be aligned with human labels.", "用 Lakeflow Jobs 给循环排程。trace 和带标注的反馈是原材料。评估数据集从生产 trace 中不断积累，裁判可以用人工标注来校准。"),
    watsonx: t("Schedule jobs outside Orchestrate and write results to a governed store. Monitors in watsonx.governance provide drift signals.", "在 Orchestrate 之外给任务排程，并把结果写入受管控的存储。watsonx.governance 的监控提供漂移信号。"),
    codex: t("A scheduled headless run can review logs and propose changes to AGENTS.md or skills as a pull request for review.", "定时的无界面运行可以审阅日志，并以 pull request 的形式提出对 AGENTS.md 或技能的修改，供人审查。"),
    cursor: t("Background agents can do the same review and open a pull request.", "后台智能体可以做同样的审阅并发起 pull request。"),
    claude: t("A scheduled headless session can read logs and propose skill or instruction edits. Keep a human merge step.", "定时的无界面会话可以读取日志，并提出对技能或指令的修改。保留人工合并这一步。"),
    other: t("A scheduler such as launchd, systemd timers, or cron, plus the same scripts.", "launchd、systemd timer 或 cron 这类调度器，加上同样的脚本。"),
  },
  checks: [
    {
      q: t("What does the loop change, and what does it never change?", "这个循环会改变什么？绝不会改变什么？"),
      a: t("It changes one file of rules and rows in the learned tables. It never changes model weights, the sealed evals, or its own gate. A rule reaches an answer only as prompt text.", "它会改变一个规则文件和学到的那些表里的数据。它绝不改变模型权重、封存评估或它自己的关卡。规则只能以提示词文本的形式影响回答。"),
    },
    {
      q: t("Why is evidence keyed by day and origin?", "为什么证据要以日期和来源为键？"),
      a: t("Ten copies of one paragraph are one source. Two failures in one session are one event. Counting them as many lets repetition pass for evidence.", "同一段话的十份副本是一个来源。同一次会话里的两次失败是一个事件。把它们当成多个来计数，就会让重复冒充证据。"),
    },
    {
      q: t("The gate passed. Why run the sealed eval as well?", "关卡已经通过了。为什么还要运行封存评估？"),
      a: t("The gate shows the failure is real and recurring. It does not show the proposed rule fixes it, or that it breaks nothing else. Only the eval shows that.", "关卡说明这个失败是真实且反复出现的。它说明不了拟议的规则能修好它，也说明不了规则不会破坏别的东西。只有评估能说明这些。"),
    },
    {
      q: t("What does the lab not prove about self-evolution?", "关于自进化，lab 没有证明什么？"),
      a: t("That a real model follows a learned rule. The fake model's script contains the behavior. With a real model you find out from the sealed eval, run several times.", "没有证明真实模型会遵守学到的规则。假模型的脚本里本来就写了这种行为。对真实模型，要通过多次运行封存评估才能知道。"),
    },
    {
      q: t("Name every earlier module this loop depends on and what it takes from each.", "说出这个循环依赖的每个前序模块，以及从每个模块取用了什么。"),
      a: t("Harness: the logs. State: the cursor, the learned tables, the reset. Tools: the registry to re-run calls. Evaluation: the seal and the agent eval. Guardrails: the observe-first practice. Multi-agent: the two-vote check, for document claims.", "Harness：日志。状态：游标、学到的表、重置方法。工具：用于重新执行调用的注册表。评估：封存机制和智能体评估。护栏：先观察的做法。多智能体：用于文档论断的双票核查。"),
    },
  ],
  terms: [
    { term: t("Candidate", "候选项"), def: t("A finding recorded and not yet trusted.", "已记录但尚未被信任的发现。") },
    { term: t("Corroboration", "印证"), def: t("Support from independent origins or separate days.", "来自独立来源或不同日期的支持。") },
    { term: t("Promotion gate", "晋升关卡"), def: t("The rule that decides when a candidate may become a rule.", "决定候选项何时可以成为规则的条件。") },
    { term: t("Report mode", "报告模式"), def: t("The loop runs every step and writes nothing.", "循环执行每一步，但不写入任何东西。") },
  ],
};
