import { t, type Module } from "@/lib/types";

export const state: Module = {
  id: "state",
  n: 4,
  layer: 1,
  title: t("State and storage", "状态与存储"),
  short: t(
    "Where facts live between calls, who may write them, and how concurrent writers stay safe.",
    "两次调用之间数据存在哪里、谁可以写，以及多个写入方如何互不破坏。",
  ),
  what: t(
    "State is everything that outlives one model call: the run state inside a request, the conversation across requests, durable knowledge and memory, and the cursors that mark how far a background job has read.",
    "状态是比一次模型调用活得更久的一切：单次请求内的运行状态、跨请求的对话、持久化的知识与记忆，以及标记后台任务读到哪里的游标。",
  ),
  why: t(
    "A model call has no memory. Each kind of state has a different lifetime and owner, and mixing them causes the worst bugs. The reference build's single-writer stores failed when two scheduled jobs wrote at once, and one file was corrupted.",
    "模型调用本身没有记忆。每种状态的生命周期和所有者都不同，混在一起会导致最严重的问题。参考系统早期使用单写入方的存储，两个定时任务同时写入时出了故障，其中一个文件被损坏。",
  ),
  how: [
    t("Run state is a dict passed through the executor. Merge rules say which keys accumulate and which overwrite.", "运行状态是在执行器中传递的字典。合并规则规定哪些键累加、哪些键覆盖。"),
    t("Conversation state is rows keyed by user and thread.", "对话状态是以用户和会话为键的数据行。"),
    t("Durable state is tables whose name prefix shows the owner: kb for ingested, brain for learned, mem for per-user.", "持久状态是表，表名前缀标明归属：kb 是入库内容，brain 是学到的内容，mem 是每个用户的记忆。"),
    t("Background jobs keep a cursor so they resume where they stopped and never handle a log line twice.", "后台任务保存游标，中断后从上次的位置继续，同一行日志绝不处理两次。"),
  ],
  prereqs: [],
  inBuild: [
    { path: "apps/agent-server/graph.py", role: t("merge_state: the rules for run state.", "merge_state：运行状态的合并规则。") },
    { path: "apps/agent-server/pgstore.py", role: t("Connection handling and schema setup for Postgres.", "Postgres 的连接管理和建表。") },
    { path: "apps/agent-server/pgschema.sql", role: t("Schemas by owner: learned knowledge, file ledger, chunk indexes.", "按归属划分的 schema：学到的知识、文件台账、文本块索引。") },
    { path: "apps/agent-server/conversation_store.py", role: t("Threads and messages across requests.", "跨请求的会话和消息。") },
  ],
  flow: {
    caption: t("Three lifetimes, three places", "三种生命周期，三个存放位置"),
    stages: [
      { label: t("Run state", "运行状态"), detail: t("Lives for one request. A dict. Dies when the answer is returned.", "只存在于一次请求内。是一个字典。回答返回后即消失。"), kind: "input" },
      { label: t("Conversation", "对话"), detail: t("Lives for a thread. Rows with user, thread, role, content.", "存在于一个会话期间。数据行包含用户、会话、角色、内容。"), kind: "store" },
      { label: t("Ingested knowledge", "入库的知识"), detail: t("kb tables. Written by the indexer. Rebuildable from the bank.", "kb 表。由索引程序写入。可以从知识库重建。"), kind: "store" },
      { label: t("Learned knowledge", "学到的知识"), detail: t("brain tables. Written by the nightly loop. Can be dropped without touching kb.", "brain 表。由夜间任务写入。删除它不影响 kb。"), kind: "store" },
      { label: t("User memory", "用户记忆"), detail: t("mem tables. Every row carries a partition.", "mem 表。每一行都带有分区标识。"), kind: "store" },
      { label: t("Cursors", "游标"), detail: t("One number per job: how far into a log it has read.", "每个任务一个数字：它读到日志的哪个位置。"), kind: "check" },
    ],
  },
  steps: [
    {
      id: "lifetimes",
      title: t("Name each kind of state and its owner", "给每种状态命名，并确定归属"),
      why: t("Decide ownership before creating a single table. A table with two owners is where concurrent-write bugs and privacy leaks start.", "在建任何一张表之前先确定归属。一张表有两个所有者，正是并发写入问题和隐私泄露的起点。"),
      do: [
        t("List what must outlive a request. For each item write: lifetime, the one job that writes it, who reads it.", "列出哪些数据必须活过一次请求。对每一项写下：生命周期、唯一负责写入的任务、谁来读。"),
        t("Group them under prefixes: kb, brain, mem, conv, job.", "按前缀分组：kb、brain、mem、conv、job。"),
      ],
      verify: t("Every table in your plan has exactly one writer.", "规划中的每张表都只有一个写入方。"),
      produces: t("An ownership table: prefix, writer, readers, lifetime.", "一张归属表：前缀、写入方、读取方、生命周期。"),
    },
    {
      id: "connect",
      title: t("Open the database so concurrent access works", "以支持并发访问的方式打开数据库"),
      why: t("Connection settings come before schema because they decide whether a second writer waits or fails. Fixing this after jobs exist means finding it as a corrupted file.", "连接设置排在建表之前，因为它决定第二个写入方是等待还是失败。等任务都跑起来再改，往往是通过文件损坏才发现问题。"),
      do: [
        t("Enable write-ahead logging so readers proceed while a writer writes.", "开启预写日志（WAL），这样写入时读取不受阻塞。"),
        t("Set a busy timeout so a second writer waits its turn.", "设置 busy timeout，让第二个写入方排队等待。"),
        t("Use one `connect()` function everywhere.", "全系统只用一个 `connect()` 函数。"),
      ],
      lab: { file: "labs/m04_state/store.py", region: "connect" },
      verify: t("`PRAGMA journal_mode` returns wal.", "`PRAGMA journal_mode` 返回 wal。"),
      needs: [{ step: "state.lifetimes", what: t("the list of jobs that will write at the same time", "会同时写入的任务清单") }],
      produces: t("`connect()`: the only way the stack opens its database.", "`connect()`：全系统打开数据库的唯一方式。"),
    },
    {
      id: "schema",
      title: t("Create the schema, grouped by owner", "按归属分组建表"),
      why: t("Schema follows ownership. Every later module writes into one of these tables, so they are created once here and never altered ad hoc.", "表结构由归属决定。后面每个模块都会往其中某张表里写数据，所以在这里一次建好，之后不做临时修改。"),
      do: [
        t("Read the schema below. Find the prefix of each table.", "阅读下面的表结构，找出每张表的前缀。"),
        t("Note `chunk_id` is `<source>::<n>`. Retrieval and evals rely on that format.", "注意 `chunk_id` 的格式是 `<source>::<n>`。检索和评估都依赖这个格式。"),
        t("Make schema creation idempotent and call it on every start.", "让建表操作幂等，并在每次启动时调用。"),
      ],
      lab: { file: "labs/m04_state/store.py", region: "schema" },
      run: "python3 -m labs.m04_state.demo",
      output: "m04.demo",
      pick: ["1 "],
      verify: t("Running `ensure_schema` twice raises no error and changes nothing.", "运行两次 `ensure_schema` 不报错，也不改变任何东西。"),
      needs: [
        { step: "state.lifetimes", what: t("prefixes and owners", "前缀和归属") },
        { step: "state.connect", what: t("a connection", "数据库连接") },
      ],
      produces: t("Tables for chunks, edges, claims, memory, turns, and cursors.", "文本块、边、论断、记忆、对话轮次和游标的表。"),
    },
    {
      id: "merge",
      title: t("Define merge rules for run state", "定义运行状态的合并规则"),
      why: t("This must exist before any code runs two nodes at once. Without it, the second tool result silently replaces the first.", "在任何代码同时运行两个节点之前，这套规则就必须存在。否则第二个工具的结果会悄悄覆盖第一个。"),
      do: [
        t("Keys ending in `_append` extend a list.", "以 `_append` 结尾的键向列表追加。"),
        t("Counter keys add.", "计数类的键做加法。"),
        t("Every other key overwrites. That is a decision: last writer wins.", "其余的键直接覆盖。这是有意的决定：后写的生效。"),
      ],
      lab: { file: "labs/m04_state/store.py", region: "merge" },
      output: "m04.demo",
      pick: ["2 "],
      verify: t("Two updates that each append a message leave both messages in the list.", "两个各自追加一条消息的更新，合并后列表里两条都在。"),
      produces: t("`merge_state()`: used by the wave executor in the harness.", "`merge_state()`：Harness 里的波次执行器会用到它。"),
    },
    {
      id: "writers",
      title: t("Test concurrent writers before you depend on them", "在依赖并发写入之前先测试"),
      why: t("It needs the connection and the schema. It is here, and not in operations, because a failure changes the storage choice.", "它需要连接和表结构都就绪。放在这里而不是运维模块，是因为一旦失败就要改变存储方案。"),
      do: [
        t("Start three threads, each with its own connection, each inserting 200 rows.", "启动三个线程，各用自己的连接，各插入 200 行。"),
        t("Count the rows.", "统计行数。"),
      ],
      output: "m04.demo",
      pick: ["3 "],
      verify: t("600 rows, no `database is locked` error.", "共 600 行，没有出现 `database is locked` 错误。"),
      needs: [
        { step: "state.connect", what: t("WAL and busy timeout", "WAL 和 busy timeout") },
        { step: "state.schema", what: t("a table to write to", "可写入的表") },
      ],
      produces: t("Proof that a chat, a nightly job, and an eval can write at the same time.", "证明聊天、夜间任务和评估可以同时写入。"),
    },
    {
      id: "cursor",
      title: t("Give every background job a cursor", "给每个后台任务一个游标"),
      why: t("Jobs that read logs come later, in evaluation and self-evolution. The cursor is built now because it is storage, and those jobs assume it.", "读取日志的任务在后面的评估和自进化模块才出现。游标现在就建好，因为它属于存储层，而那些任务默认它已存在。"),
      do: [
        t("Store one byte offset per job name.", "为每个任务名保存一个字节偏移量。"),
        t("Read from the offset to the last complete line. Advance the offset in the same call.", "从偏移量读到最后一个完整的行，并在同一次调用中推进偏移量。"),
        t("If the file is now smaller than the stored offset, it was rotated: start again from 0. Without this check the job skips every line written after rotation. Lab 15 shows it.", "如果文件现在比保存的偏移量还小，说明它被轮转过：从 0 重新开始。没有这项检查，任务会跳过轮转之后写入的每一行。lab 15 演示了这一点。"),
        t("Write logs as JSON lines, one record per line.", "日志使用 JSON Lines 格式，每行一条记录。"),
      ],
      lab: { file: "labs/m04_state/store.py", region: "cursor" },
      output: "m04.demo",
      pick: ["4 "],
      verify: t("Three lines are read once, one new line is read next, and a third call returns nothing.", "先读到三行，接着读到一行新的，第三次调用返回空。"),
      needs: [{ step: "state.schema", what: t("the job_cursors table", "job_cursors 表") }],
      produces: t("`read_new_lines()` and `append_log()`.", "`read_new_lines()` 和 `append_log()`。"),
    },
    {
      id: "reset",
      title: t("Check that learned state can be dropped alone", "确认学到的状态可以单独清除"),
      why: t("Do this before any learning job exists. It is the test of the ownership boundary, and it is your recovery plan when a learner writes something wrong.", "要在任何学习任务出现之前做这件事。它检验归属边界是否成立，也是学习任务写错内容时的恢复方案。"),
      do: [
        t("Drop every table with the brain prefix.", "删除所有以 brain 为前缀的表。"),
        t("Confirm the kb tables are untouched.", "确认 kb 表没有受影响。"),
      ],
      output: "m04.demo",
      pick: ["5 "],
      verify: t("The kb tables are all still present.", "kb 表全部还在。"),
      needs: [{ step: "state.schema", what: t("prefixes that mark ownership", "标明归属的前缀") }],
      produces: t("A tested answer to: how do I delete everything the agent taught itself?", "一个经过验证的答案：如何删除智能体自己学到的一切？"),
    },
    {
      id: "postgres",
      title: t("Move to Postgres when the workload asks for it", "当负载需要时迁移到 Postgres"),
      why: t("It is last because the lab database is enough to learn every later module. Move when you have several writers under load, need a vector index over many rows, or need point-in-time recovery.", "它排在最后，因为 lab 用的数据库足够学完后面所有模块。当你有多个高负载写入方、需要对大量数据建向量索引，或需要按时间点恢复时，再迁移。"),
      do: [
        t("Start Postgres with the pgvector extension. On your machine use the container command below. The lab starts a private throwaway cluster instead.", "启动带 pgvector 扩展的 Postgres。在你自己的机器上用下面的容器命令。lab 则会启动一个用完即删的私有集群。"),
        t("Map each table prefix to a Postgres schema of the same name: kb, brain, mem.", "把每个表前缀映射为同名的 Postgres schema：kb、brain、mem。"),
        t("Keep the same column names so calling code keeps its SQL.", "保持列名不变，这样调用代码的 SQL 不用改。"),
        t("Run the concurrent-writer test against Postgres. Each writer uses its own connection.", "在 Postgres 上运行并发写入测试。每个写入方使用自己的连接。"),
      ],
      lab: { file: "labs/m05_rag/pg.py", region: "writers" },
      code: { lang: "bash", file: "on your machine", text: `docker run -d --name agentdb -e POSTGRES_PASSWORD=change-me -p 127.0.0.1:5432:5432 pgvector/pgvector:pg17
psql -h 127.0.0.1 -U postgres -c "CREATE EXTENSION IF NOT EXISTS vector;"
psql -h 127.0.0.1 -U postgres -c "CREATE SCHEMA kb; CREATE SCHEMA brain; CREATE SCHEMA mem;"
# "delete everything the agent taught itself" becomes:  DROP SCHEMA brain CASCADE;` },
      codeNote: t("The container command was not run by the labs. The lab ran the same schema and writer test on a local Postgres 16 server.", "lab 没有运行这条容器命令。lab 在本地的 Postgres 16 上运行了同样的 schema 和写入测试。"),
      run: "PG_RUN_AS=<ordinary user, only when running as root> python3 -m labs.m05_rag.pg",
      output: "m05.pg",
      pick: ["1 ", "2 "],
      verify: t("The schema applies twice without error, and three writers insert 600 rows with no lock errors.", "schema 连续应用两次不报错，三个写入方写入 600 行且没有锁错误。"),
      needs: [{ step: "state.writers", what: t("the test that tells you the move worked", "用来确认迁移成功的测试") }],
      produces: t("A production store with the same layout.", "一个结构相同的生产级存储。"),
    },
  ],
  together: [
    { with: "harness", how: t("The wave executor calls merge_state after every wave.", "波次执行器在每一波结束后调用 merge_state。") },
    { with: "rag-graph", how: t("Chunks, vectors, and graph edges live in the kb tables.", "文本块、向量和图的边存放在 kb 表里。") },
    { with: "memory", how: t("Facts and conversation turns live in mem and conv tables, always with a partition.", "事实和对话轮次存放在 mem 和 conv 表里，始终带有分区。") },
    { with: "self-evolving", how: t("Claims and their evidence live in brain tables. Log readers use cursors.", "论断及其证据存放在 brain 表里。读日志的任务使用游标。") },
  ],
  failures: [
    {
      when: "2026-08",
      title: t("Two jobs wrote one single-writer file", "两个任务同时写一个单写入方文件"),
      what: t("The daily cycle and the learner collided at the same minute two nights running. One night the database was corrupted.", "日常任务和学习任务连续两晚在同一分钟撞在一起。其中一晚数据库被损坏。"),
      fix: t("A store with real concurrency control, and an explicit lock for jobs that must not overlap.", "换用真正支持并发控制的存储，并对不能重叠的任务显式加锁。"),
      lesson: t("Find out how your store handles a second writer before you have one.", "在出现第二个写入方之前，先弄清你的存储会如何处理它。"),
    },
    {
      when: "2026-09",
      title: t("A findings file that was 97 percent duplicates", "一个 97% 都是重复内容的发现记录文件"),
      what: t("A job re-recorded the same 26 findings about 11,000 times, once every hour.", "一个任务每小时把同样的 26 条发现重新记录一遍，累计约 11,000 次。"),
      fix: t("A cursor per job, and a uniqueness rule on what is recorded.", "每个任务一个游标，并对记录内容加唯一性约束。"),
      lesson: t("A job without a cursor counts its own repetition as evidence.", "没有游标的任务，会把自己的重复劳动当成证据。"),
    },
  ],
  portability: {
    databricks: t("Delta tables for durable state. Lakebase for Postgres-style transactional state such as threads and checkpoints. Run state lives in your agent code.", "持久状态用 Delta 表。会话和检查点这类事务型状态用 Lakebase（Postgres 风格）。运行状态在你的智能体代码里。"),
    watsonx: t("Orchestrate manages thread state for its agents. Durable domain state goes in watsonx.data or a database you connect.", "Orchestrate 为其智能体管理会话状态。持久的业务状态放在 watsonx.data 或你接入的数据库里。"),
    codex: t("Session history is managed by the tool and can be resumed. Durable project state is files in the repo.", "会话历史由工具管理，可以恢复。持久的项目状态是仓库里的文件。"),
    cursor: t("Chat history is managed by the editor. Durable state is files, plus whatever your MCP servers store.", "聊天历史由编辑器管理。持久状态是文件，以及你的 MCP 服务自己存的数据。"),
    claude: t("Sessions can be resumed and the SDK exposes session ids. Durable state is files and your own stores.", "会话可以恢复，SDK 提供会话 ID。持久状态是文件和你自己的存储。"),
    other: t("SQLite with WAL is enough for one machine. Postgres in a container gives the same layout with stronger guarantees.", "单机用开启 WAL 的 SQLite 就够了。容器里的 Postgres 结构相同，保障更强。"),
  },
  checks: [
    {
      q: t("Name three kinds of state and their lifetimes.", "说出三种状态及其生命周期。"),
      a: t("Run state lasts one request. Conversation state lasts a thread. Knowledge and memory last until retired. Mixing them leads to leaks across users or loss across requests.", "运行状态持续一次请求。对话状态持续一个会话。知识和记忆持续到被退役。混用会导致用户间的数据泄露，或请求间的数据丢失。"),
    },
    {
      q: t("Why are merge rules part of storage and not part of the harness?", "为什么合并规则属于存储，而不属于 Harness？"),
      a: t("They define what happens when two writers update the same state. That is a storage question. The harness only decides when nodes run.", "它定义的是两个写入方更新同一状态时会发生什么，这是存储层面的问题。Harness 只决定节点何时运行。"),
    },
    {
      q: t("Why build the cursor now when no job reads logs yet?", "现在还没有任务读日志，为什么要先做游标？"),
      a: t("Every later background job assumes it. Building it once here means no job invents its own, and none re-reads a log from the start.", "后面每个后台任务都默认它已经存在。在这里统一做好，就不会有任务各自发明一套，也不会有任务从头重读日志。"),
    },
    {
      q: t("How do you delete everything the agent taught itself, and nothing else?", "如何只删除智能体自己学到的内容，而不影响其他？"),
      a: t("Drop the brain tables. Ingested documents are in kb and user memory is in mem, so neither is touched. This works only because ownership was decided before the tables were created.", "删除 brain 表。入库文档在 kb，用户记忆在 mem，两者都不受影响。这之所以可行，是因为建表之前就确定了归属。"),
    },
  ],
  terms: [
    { term: t("WAL", "WAL（预写日志）"), def: t("Write-ahead logging. Changes go to a log first, so readers are not blocked by a writer.", "修改先写入日志，因此读取不会被写入阻塞。") },
    { term: t("Cursor", "游标"), def: t("A saved position in a log, one per job.", "日志中保存下来的位置，每个任务一个。") },
    { term: t("Partition", "分区"), def: t("The value, usually a user id, that scopes every memory read and write.", "限定每次记忆读写范围的值，通常是用户 ID。") },
  ],
};
