import { t } from "./types";

/** Interface strings. Lesson text lives in content/. */
export const ui = {
  brandA: t("Agent Build", "智能体搭建"),
  brandB: t("Tutor", "教程"),
  navMap: t("Map", "地图"),
  navPlaybook: t("Playbook", "操作手册"),
  navPlatforms: t("Platforms", "各平台"),
  navLive: t("Live build", "实时构建"),
  navTutor: t("Ask the tutor", "问导师"),
  footer: t(
    "Lessons are drawn from a working local build. Hostnames, paths, keys, and domain data are removed before publishing. Lab code and its recorded output are produced by running the labs. Platform walkthroughs are written from vendor documentation and were not executed.",
    "课程内容取材于一个实际运行的本地系统。发布前已移除主机名、路径、密钥和业务数据。lab 代码及其记录的输出来自实际运行。各平台的操作指南依据厂商文档编写，未经实际执行。",
  ),
  heroEyebrow: t("A playbook built from a working system", "源自真实系统的操作手册"),
  heroTitle: t("Build an agent stack, and know why each step comes when it does.", "搭建一套智能体系统，并明白每一步为什么排在那里。"),
  heroLede: t(
    "Fifteen modules and one runnable lab for each. Every step states what it uses from earlier steps, what it produces, and how you know it worked. Code and expected output come from labs that were actually run.",
    "十五个模块，每个模块配一个可运行的 lab。每一步都写明它用到前面哪些步骤的成果、它产出什么，以及如何确认它成功了。代码和预期输出都来自实际运行过的 lab。",
  ),
  startHere: t("Start the playbook", "开始操作手册"),
  runLabs: t("Run all labs", "运行全部 lab"),
  selected: t("Selected", "当前选中"),
  openLesson: t("Open lesson", "打开课程"),
  whyFirst: t("Why these come first", "为什么这些要先做"),
  nothingFirst: t("Nothing. This is a starting point.", "没有。这是一个起点。"),
  outOfOrder: t("Build out of order", "不按顺序搭建"),
  stubWith: t("Stand in with:", "可用以下替代："),
  unlocks: t("What this unlocks", "它解锁了什么"),
  legendNeeds: t("Must exist first", "必须先存在"),
  legendUnlocks: t("Unlocked next", "接下来解锁"),
  legendHint: t("Select a module. Scroll sideways on a small screen.", "点击选择模块。小屏幕上可左右滑动。"),
  steps: t("steps", "步"),
  whyTitle: t("Why does A come before B?", "为什么 A 排在 B 前面？"),
  whyLede: t(
    "Pick any two modules. If one depends on the other you get the chain of reasons. If neither does, you can build them in either order.",
    "任选两个模块。如果一个依赖另一个，你会看到一连串理由。如果互不依赖，两者的搭建顺序可以随意。",
  ),
  moduleA: t("Module A", "模块 A"),
  moduleB: t("Module B", "模块 B"),
  pickTwo: t("Pick two different modules.", "请选择两个不同的模块。"),
  comesBefore: t("comes before", "排在前面，之后是"),
  needs: t("needs", "需要"),
  independent: t("Neither depends on the other. Build them in either order, or at the same time.", "两者互不依赖。先做哪个都行，也可以同时做。"),
  bothRest: t("Both rest on:", "两者都建立在以下模块之上："),
  noShared: t("They share no prerequisites.", "它们没有共同的前置模块。"),
  allModules: t("All fifteen modules", "全部十五个模块"),
  liveTitle: t("From the live build", "来自实时构建"),
  seeChanges: t("See what changed", "查看变更"),
  // lesson
  crumbMap: t("Map", "地图"),
  module: t("Module", "模块"),
  tocWhat: t("What and why", "是什么、为什么"),
  tocOrder: t("Where it sits", "所处位置"),
  tocFlow: t("Process map", "流程图"),
  tocBuild: t("Build steps", "搭建步骤"),
  tocTogether: t("Works with", "协作关系"),
  tocFailures: t("What went wrong", "踩过的坑"),
  tocPlatforms: t("Other platforms", "其他平台"),
  tocCheck: t("Explain it back", "讲给自己听"),
  tocLive: t("Live build", "实时构建"),
  tocAsk: t("Ask", "提问"),
  what: t("What", "是什么"),
  why: t("Why", "为什么"),
  howItWorks: t("How it works", "工作原理"),
  hWhat: t("What it is and why it exists", "它是什么，为什么需要它"),
  hOrder: t("Where it sits in the build order", "它在搭建顺序中的位置"),
  needsFirst: t("Needs first", "前置模块"),
  startPoint: t("Nothing. You can start here.", "没有。可以从这里开始。"),
  unlocksH: t("Unlocks", "解锁"),
  endPoint: t("Nothing depends on this. It is an end point of the map.", "没有模块依赖它。它是地图上的一个终点。"),
  inBuild: t("In the reference build", "在参考系统中"),
  path: t("Path", "路径"),
  role: t("Role", "作用"),
  hFlow: t("Process map", "流程图"),
  loopsTo: t("loops to step", "回到第"),
  loopsToEnd: t("", "步"),
  hBuild: t("Build steps", "搭建步骤"),
  buildLede: t(
    "Follow them in order the first time. Each step names what it uses from earlier steps and what it leaves for later ones. Code is read from the lab files, and output is what the lab printed when it was run.",
    "第一次请按顺序做。每一步都写明它用到前面步骤的什么成果，又为后面的步骤留下什么。代码直接读取自 lab 文件，输出是 lab 实际运行时打印的内容。",
  ),
  whyHere: t("Why this step is here", "为什么这一步排在这里"),
  uses: t("Uses", "用到"),
  usesNothing: t("Nothing from earlier steps.", "不依赖之前的任何步骤。"),
  from: t("from", "来自"),
  doThis: t("Do this", "操作"),
  code: t("Code", "代码"),
  run: t("Run", "运行"),
  recorded: t("Recorded output", "记录的输出"),
  recordedNote: t("from running the lab offline with the fake model", "使用假模型离线运行 lab 所得"),
  doneWhen: t("You are done when", "完成标志"),
  produces: t("Produces", "产出"),
  feedsInto: t("Feeds", "供给"),
  feedsNothing: t("No later step consumes this directly.", "没有后续步骤直接使用它。"),
  notExecuted: t("Not executed in the labs", "lab 中未执行"),
  notExecutedNote: t(
    "This step describes work on your own machine or account. Its commands were not run when the labs were tested.",
    "这一步描述的是在你自己的机器或账号上的操作。测试 lab 时没有运行这些命令。",
  ),
  machineTitle: t("Checked on the reference machine", "在参考机器上的检查结果"),
  machineNone: t(
    "Not checked on a machine yet. On your own machine run the command below. It only reads, and it writes the result here when you add --write.",
    "还没有在机器上检查过。在你自己的机器上运行下面的命令。它只做读取操作；加上 --write 后会把结果写到这里。",
  ),
  machineManual: t("This step is checked by hand.", "这一步需要人工检查。"),
  open: t("open", "展开"),
  close: t("close", "收起"),
  copy: t("Copy", "复制"),
  copied: t("Copied", "已复制"),
  hTogether: t("How it works with the other parts", "它如何与其他部分协作"),
  hFailures: t("What went wrong in the real build", "真实搭建中踩过的坑"),
  failLab: t("found while building the labs", "搭建 lab 时发现"),
  whatHappened: t("What happened", "发生了什么"),
  fix: t("Fix", "修复"),
  lesson: t("Lesson", "教训"),
  hPlatforms: t("The same idea on other platforms", "同样的思路在其他平台上"),
  platform: t("Platform", "平台"),
  howMaps: t("How this module maps", "本模块如何对应"),
  fullGuide: t("Step-by-step guides per platform", "各平台的分步指南"),
  hCheck: t("Explain it back", "讲给自己听"),
  checkLede: t("Answer aloud first. Then open the answer and compare.", "先自己说一遍答案，再展开对照。"),
  strongAnswer: t("A strong answer", "参考答案"),
  canExplain: t("I can explain this module and its ordering without notes", "我可以不看笔记讲清这个模块及其顺序"),
  terms: t("Terms", "术语"),
  hLive: t("From the live build", "来自实时构建"),
  liveLede: t("Recent changes and files the sync job filed under this module. These lines are in English as written in the build.", "同步任务归到本模块下的近期变更和文件。这些内容保留了构建系统中的英文原文。"),
  hAsk: t("Ask the tutor about this module", "就本模块向导师提问"),
  prev: t("Previous module", "上一个模块"),
  next: t("Next module", "下一个模块"),
  // playbook
  pbEyebrow: t("Playbook", "操作手册"),
  pbTitle: t("Every step, in an order that works", "每一步，按可行的顺序排列"),
  pbLede: t(
    "This is one valid order for all steps: each comes after everything it uses. Tick steps as you finish them. Your progress is kept in this browser.",
    "这是全部步骤的一种可行顺序：每一步都排在它所依赖的步骤之后。完成一步就勾选一步。进度保存在当前浏览器里。",
  ),
  pbProgress: t("done", "已完成"),
  pbFilter: t("Show", "显示"),
  pbAll: t("All steps", "全部步骤"),
  pbLab: t("Lab steps only", "仅 lab 步骤"),
  pbTodo: t("Not done yet", "尚未完成"),
  pbGoal: t("I want to build", "我想搭建"),
  pbGoalAll: t("everything", "全部"),
  pbGoalNote: t("Showing only the steps this module needs, in order.", "只显示该模块所需的步骤，按顺序排列。"),
  pbSetup: t("Before step 1", "第 1 步之前"),
  pbSetupBody: t(
    "Clone the repository and run every lab once against the fake model. This takes about 20 seconds and proves your Python works before any model is involved.",
    "克隆仓库，用假模型把所有 lab 运行一遍。大约需要 20 秒，可以在涉及任何模型之前先确认 Python 环境正常。",
  ),
  // platforms
  plEyebrow: t("Carry it elsewhere", "迁移到别处"),
  plTitle: t("Every module on every platform", "每个模块在每个平台上的对应"),
  plLede: t(
    "The parts stay the same across platforms. What changes is who runs each part: you, or the platform. Open a platform for a step-by-step guide.",
    "各部件在不同平台上是一样的，变的是每个部件由谁来运行：你，还是平台。点开某个平台可以看分步指南。",
  ),
  plWarn: t(
    "These guides were written from vendor documentation read in October 2026. None was executed: there was no account on these platforms. Product names change often. Confirm each command against the linked source before you rely on it.",
    "这些指南依据 2026 年 10 月查阅的厂商文档编写。全部未经实际执行：编写时没有这些平台的账号。产品名称经常变化。使用前请对照链接的来源逐条核实命令。",
  ),
  youOwn: t("What you own", "归你负责的"),
  platformOwns: t("What the platform runs", "由平台运行的"),
  guide: t("Guide", "指南"),
  matrix: t("Matrix", "对照表"),
  correspondsTo: t("Corresponds to", "对应"),
  sources: t("Sources", "来源"),
  noSources: t("No vendor documentation is needed. The labs are the reference.", "不需要厂商文档。以 lab 为准。"),
  // live
  lvEyebrow: t("Live build", "实时构建"),
  lvTitle: t("What changed in the reference build", "参考系统里发生了哪些变化"),
  lvLede: t(
    "A job on the build machine scans the project, removes anything sensitive, sorts each change into a module, and pushes a snapshot here. Entries stay in English as written.",
    "构建机器上的一个任务扫描项目、移除敏感内容、把每项变更归入某个模块，然后把快照推送到这里。条目保留英文原文。",
  ),
  lvNone: t("No snapshot yet. On the build machine run", "还没有快照。请在构建机器上运行"),
  lvSnapshot: t("snapshot date (UTC)", "快照日期（UTC）"),
  lvChanges: t("changes", "项变更"),
  lvNotes: t("design notes", "篇设计笔记"),
  lvFiles: t("source files", "个源文件"),
  lvRedactions: t("redactions applied", "处脱敏"),
  lvEvals: t("Latest eval runs", "最近的评估运行"),
  lvRecent: t("Recent changes", "近期变更"),
  lvRecentLede: t("Each line is a commit subject. They are written as lessons learned.", "每一行是一条提交标题。它们以“学到了什么”的方式书写。"),
  lvDesign: t("Design notes", "设计笔记"),
  lvSource: t("Source files", "源文件"),
  stChecking: t("Checking the local build", "正在检查本地系统"),
  stUp: t("Local build reachable", "本地系统可访问"),
  stDown: t("Local build not reachable right now. Showing the last pushed snapshot.", "本地系统暂时无法访问。显示的是最近一次推送的快照。"),
  stUnset: t("Live link not configured yet. Showing the pushed snapshot.", "尚未配置实时连接。显示的是已推送的快照。"),
  // tutor
  tuEyebrow: t("Tutor", "导师"),
  tuTitle: t("Ask about any part of the build", "就搭建过程的任何部分提问"),
  tuLede: t(
    "Questions go to the local model when the build machine is reachable, and to a cloud model otherwise. For questions about one module, use the tutor at the bottom of that lesson. It is given the full lesson as context.",
    "构建机器可访问时，问题会发给本地模型；否则发给云端模型。针对某个模块的问题，请使用该课程底部的导师，它会拿到完整的课程内容作为上下文。",
  ),
  tuAsk: t("Ask", "提问"),
  tuPlaceholder: t("Ask about any part of the build", "就搭建过程的任何部分提问"),
  tuPlaceholderTopic: t("Ask about", "提问："),
  tuThinking: t("Thinking. A cold local model can take up to a minute.", "思考中。本地模型冷启动时可能需要一分钟。"),
  tuVia: t("answered by", "回答来自"),
  tuLocal: t("the local model", "本地模型"),
  tuCloud: t("a cloud model", "云端模型"),
  tuS1: t("Quiz me on why this module sits where it does.", "考考我：这个模块为什么排在这个位置？"),
  tuS2: t("What would I stub to build this first?", "如果想先做这个，我需要用什么来替代前置模块？"),
  tuS3: t("How would I build this on Databricks?", "在 Databricks 上该怎么搭建这个？"),
  tuError: t("The tutor could not be reached.", "无法连接到导师。"),
  navDbx: t("Databricks", "Databricks"),
  dbxEyebrow: t("Replication guide", "复刻指南"),
  dbxNotRun: t("Not executed on Databricks", "未在 Databricks 上执行"),
  dbxChecked: t("What was checked here", "在这里检查过的内容"),
  dbxCheckedLede: t("Run by replicate/databricks/check.py on", "由 replicate/databricks/check.py 运行于"),
  dbxFilesCompile: t("Python files compile", "个 Python 文件可编译"),
  dbxYaml: t("YAML files parse", "个 YAML 文件可解析"),
  dbxBash: t("shell scripts pass bash -n", "个 shell 脚本通过 bash -n"),
  dbxSql: t("SQL files read, not parsed (no Databricks SQL engine here)", "个 SQL 文件仅阅读，未解析（这里没有 Databricks SQL 引擎）"),
  dbxTests: t("portable tests passed", "项可移植测试通过"),
  dbxTestNames: t("Test names", "测试名称"),
  dbxMapTitle: t("What moves where", "什么搬到哪里"),
  dbxMapLede: t("Each part of the local build, where it lives on Databricks, and what changes in the move.", "本地构建的每个部分、它在 Databricks 上的位置，以及迁移中发生的变化。"),
  dbxLocal: t("Local build", "本地构建"),
  dbxOn: t("On Databricks", "在 Databricks 上"),
  dbxChange: t("What changes", "变化"),
  dbxStep: t("Step", "步骤"),
  dbxOrderTitle: t("Build order and dependencies", "构建顺序与依赖"),
  dbxOrderLede: t("Click a step to see what it needs (green) and what it unlocks (purple). Steps in the same phase with no line between them can be built in either order.", "点击某一步，查看它需要什么（绿色）和它解锁什么（紫色）。同一阶段中彼此没有连线的步骤，先做哪个都可以。"),
  dbxNeeds: t("needs", "需要"),
  dbxUnlocks: t("unlocks", "解锁"),
  dbxOneOf: t("one of", "其中之一"),
  dbxNoDependents: t("No later step depends on this one.", "后面没有步骤依赖这一步。"),
  dbxReplaces: t("Replaces", "替代"),
  dbxAfter: t("Do first", "先完成"),
  dbxLessons: t("Lessons behind this step", "这一步背后的课程"),
  dbxWhy: t("Why this step, and why here", "为什么要做这一步，为什么在这里"),
  dbxWhat: t("What it does", "它做什么"),
  dbxHow: t("How to do it", "怎么做"),
  dbxScripts: t("Scripts", "脚本"),
  dbxInterpret: t("How to read the result", "如何解读结果"),
  dbxTrouble: t("Troubleshooting", "排障"),
  dbxSymptom: t("You see", "现象"),
  dbxCause: t("Why", "原因"),
  dbxFix: t("Do this", "处理"),
  dbxDone: t("Done when", "完成标准"),
  dbxUnconfirmed: t("Not confirmed on a vendor page", "未在厂商页面上确认"),
  dbxPlaybook: t("Playbook: running it on Databricks", "操作手册：在 Databricks 上运行它"),
  dbxIncidents: t("When something breaks", "出问题时"),
  dbxFirstCheck: t("First check", "先检查"),
  dbxCost: t("Cost levers", "成本杠杆"),
  dbxGaps: t("What does not carry over", "哪些无法沿用"),
  dbxOpenAll: t("Open all steps", "展开所有步骤"),
  dbxCloseAll: t("Close all steps", "收起所有步骤"),
  dbxCard: t("A full step-by-step replication of the local build on Databricks, with scripts, interpretation, troubleshooting and a run playbook.", "在 Databricks 上完整复刻本地构建的分步指南，含脚本、结果解读、排障和运行手册。"),
} as const;
